# Generated by Django 5.1.5 on 2026-06-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='Временный file_path')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('card_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_cache', to='tarot.tarotcarditem', verbose_name='Карта в колоде')),
            ],
            options={
                'verbose_name': 'Tarot: Кэш путей файлов',
                'verbose_name_plural': 'Tarot: Кэши путей файлов',
            },
        ),
    ]
