# Generated by Django 5.1.5 on 2026-06-10 08:06

import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    TarotCardItem = apps.get_model('tarot', 'TarotCardItem')
    BotFile = apps.get_model('tarot', 'BotFile')
    Bot = apps.get_model('tg_bot', 'Bot')
    
    # Берем первого попавшегося бота для переноса (или укажи нужный тип)
    bot = Bot.objects.first() 
    if not bot:
        return

    for item in TarotCardItem.objects.all():
        if item.img_id:  # Пока старое поле еще существует
            bot_file, _ = BotFile.objects.get_or_create(
                bot=bot, 
                file_id=item.img_id
            )
            item.file_info = bot_file
            item.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_tarotfilecache'),
        ('tg_bot', '0032_remove_extendedmeaning_category_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Файл бота',
                'unique_together': {('bot', 'file_id')},
            },
        ),
        migrations.AddField(
            model_name='tarotcarditem',
            name='file_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarot.botfile', verbose_name='Файл в Telegram'),
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='tarotcarditem',
            name='img_id',
        ),
    ]
