# Generated by Django 5.1.5 on 2026-06-10 09:57

import django.db.models.deletion
from django.db import migrations, models

def migrate_img_ids_to_botfile(apps, schema_editor):
    # Получаем модели
    OraculumItem = apps.get_model('tarot', 'OraculumItem')
    TarotCardItem = apps.get_model('tarot', 'TarotCardItem')
    BotFile = apps.get_model('tarot', 'BotFile')
    Bot = apps.get_model('tg_bot', 'Bot')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Получаем бота с ID 1
    bot = Bot.objects.get(pk=1)

    # Получаем ContentType для моделей
    ct_oraculum = ContentType.objects.get_for_model(OraculumItem)
    ct_tarot = ContentType.objects.get_for_model(TarotCardItem)

    # Перенос из OraculumItem
    for item in OraculumItem.objects.all():
        if item.img_id:
            BotFile.objects.get_or_create(
                bot=bot,
                file_id=item.img_id,
                content_type=ct_oraculum,
                object_id=item.pk
            )

    # Перенос из TarotCardItem
    for item in TarotCardItem.objects.all():
        if item.img_id:
            BotFile.objects.get_or_create(
                bot=bot,
                file_id=item.img_id,
                content_type=ct_tarot,
                object_id=item.pk
            )
            
def reverse_migrate_img_ids(apps, schema_editor):
    # Получаем модели
    OraculumItem = apps.get_model('tarot', 'OraculumItem')
    TarotCardItem = apps.get_model('tarot', 'TarotCardItem')
    BotFile = apps.get_model('tarot', 'BotFile')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct_oraculum = ContentType.objects.get_for_model(OraculumItem)
    ct_tarot = ContentType.objects.get_for_model(TarotCardItem)

    # Удаляем только те записи, которые были созданы для наших моделей
    BotFile.objects.filter(content_type__in=[ct_oraculum, ct_tarot], bot_id=1).delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tarot', '0002_tarotfilecache'),
        ('tg_bot', '0033_bot_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcarditem',
            name='img_id',
            field=models.CharField(help_text='Идентификатор файла (например, изображения карты).', max_length=255, verbose_name='ID файла'),
        ),
        migrations.CreateModel(
            name='BotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.bot', verbose_name='Бот')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'TG file ID для ботов',
                'verbose_name_plural': 'TG file IDs для ботов',
                'unique_together': {('bot', 'file_id')},
            },
        ),
        migrations.RunPython(migrate_img_ids_to_botfile, reverse_code=reverse_migrate_img_ids),
    ]
