# Generated by Django 5.1.5 on 2026-06-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_alter_tarotcarditem_img_id_botfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraculumitem',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='tarotcarditem',
            name='img_id',
        ),
    ]
