# Generated by Django 5.1.5 on 2026-06-10 08:31

import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    OraculumItem = apps.get_model('tarot', 'OraculumItem')
    BotFile = apps.get_model('tarot', 'BotFile')
    Bot = apps.get_model('tg_bot', 'Bot')
    
    bot = Bot.objects.filter(bot_type='TarotBot').first() # Берем конкретный тип
    if not bot:
        return

    for item in OraculumItem.objects.all():
        # Берем значение из старого поля
        old_img_id = getattr(item, 'img_id', None)
        
        if old_img_id:
            bot_file, _ = BotFile.objects.get_or_create(
                bot=bot, 
                file_id=old_img_id
            )
            # Присваиваем ID записи
            item.file_info_id = bot_file.id
            item.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_remove_tarotcarditem_img_id_botfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraculumitem',
            name='file_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarot.botfile', verbose_name='Файл в Telegram'),
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='oraculumitem',
            name='img_id',
        ),
    ]
