# Generated by Django 5.2.15 on 2026-06-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0004_remove_oraculumitem_img_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='Временный file_path')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('bot_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_cache', to='tarot.botfile', verbose_name='Bot файл')),
            ],
            options={
                'verbose_name': 'Tarot: Кэш путей файлов',
                'verbose_name_plural': 'Tarot: Кэши путей файлов',
            },
        ),
        migrations.DeleteModel(
            name='TarotFileCache',
        ),
    ]
