# Generated by Django 5.2.15 on 2026-06-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_botfilecache_delete_tarotfilecache'),
        ('tg_bot', '0034_botfile_botfilecache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botfilecache',
            name='bot_file',
        ),
        migrations.DeleteModel(
            name='BotFile',
        ),
        migrations.DeleteModel(
            name='BotFileCache',
        ),
    ]
