# Generated by Django 5.2.15 on 2026-06-12 10:05

import django.db.models.deletion
from django.db import migrations, models


def move_old_readings_to_new_table(apps, schema_editor):
    try:
        OldTarotReading = apps.get_model('tarot', 'TarotUserReading')
    except LookupError:
        return

    NewUserReading = apps.get_model('tarot', 'UserReading')
    old_readings = OldTarotReading.objects.all()
    
    new_objects = []
    for old in old_readings:
        clean_text = old.text.strip() if old.text else ""
        category = 'tarot'  # Дефолт, если совпадений не найдено
        
        # Разбираем категорию на основе префиксов в тексте лога
        if clean_text.startswith("ТАРО РАСКЛАД:"):
            category = 'canvas_spread'
            clean_text = clean_text[len("ТАРО РАСКЛАД:"):].strip()
        elif clean_text.startswith("ТАРО:"):
            category = 'tarot'
            clean_text = clean_text[len("ТАРО:"):].strip()
        elif clean_text.startswith("ONE:"):
            category = 'one'
            clean_text = clean_text[len("ONE:"):].strip()
        elif clean_text.startswith("ОРАКУЛ:"):
            category = 'oracle'
            clean_text = clean_text[len("ОРАКУЛ:"):].strip()
        elif clean_text.startswith("FUTARK:"):
            category = 'runes'
            clean_text = clean_text[len("FUTARK:"):].strip()

        # Грубый анализ формата (если в тексте есть запятые между картами или рунами — скорее всего triplet)
        # Для рун проверяем наличие нескольких символов <b>
        if category in ['tarot', 'oracle', 'canvas_spread'] and clean_text.count(',') >= 2:
            reading_format = 'triplet'
        elif category == 'runes' and clean_text.count('<b>') >= 3:
            reading_format = 'triplet'
        else:
            reading_format = 'single'

        new_objects.append(
            NewUserReading(
                id=old.id,
                user_id=old.user_id,
                text=clean_text,  # Сохраняем очищенный от маркера текст
                message_id=old.message_id,
                category=category,
                reading_format=reading_format,
                is_flipped_allowed="Перевернуто" in old.text or "(Перевернутая)" in old.text,
                is_major_only=False,  # В старых логах этот флаг явно не вытащить без полноценного NLP, оставляем False
                deck_id=None,
                created_at=old.date,
                updated_at=old.date,
            )
        )
    
    if new_objects:
        NewUserReading.objects.bulk_create(new_objects, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_remove_botfilecache_bot_file_delete_botfile_and_more'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('one', 'Одна карта)'), ('tarot', 'Таро'), ('oracle', 'Оракул'), ('runes', 'Руны (Футарк)'), ('canvas_spread', 'Расклад на холсте')], default='tarot', max_length=20, verbose_name='Категория гадания')),
                ('reading_format', models.CharField(choices=[('single', '1 карта/руна'), ('triplet', '3 карты/руны'), ('special', 'Особый расклад')], default='single', max_length=20, verbose_name='Формат расклада')),
                ('is_flipped_allowed', models.BooleanField(default=False, verbose_name='С перевернутыми')),
                ('is_major_only', models.BooleanField(default=False, verbose_name='Только Старшие Арканы')),
                ('deck_id', models.IntegerField(blank=True, null=True, verbose_name='ID колоды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата гадания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.TextField(blank=True, verbose_name='Текст гадания')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_readings', to='tg_bot.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Tarot: Пользовательское гадание',
                'verbose_name_plural': 'Tarot: Пользовательские гадания',
                'indexes': [models.Index(fields=['user', 'category', 'created_at'], name='tarot_userr_user_id_131fee_idx')],
            },
        ),
        
        migrations.RunPython(move_old_readings_to_new_table, reverse_code=migrations.RunPython.noop),
    ]