# Generated by Django 5.2.15 on 2026-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0007_userreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreading',
            name='reading_format',
        ),
        migrations.AddField(
            model_name='userreading',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество карт/рун'),
        ),
        migrations.DeleteModel(
            name='TarotUserReading',
        ),
    ]
