# Generated by Django 5.2.15 on 2026-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0009_fix_userreading_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='card_ids',
            field=models.JSONField(blank=True, default=list, help_text='Список идентификаторов карт в формате JSON, например: [12, 45, 3]', verbose_name='ID выпавших карт/рун'),
        ),
    ]
