# Generated by Django 5.2.15 on 2026-06-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0010_userreading_card_ids'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Бот, через который выполнено гадание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_readings', to='tg_bot.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='userreading',
            name='category',
            field=models.CharField(choices=[('one', 'Одна карта'), ('tarot', 'Таро'), ('oracle', 'Оракул'), ('runes', 'Руны (Футарк)'), ('canvas_spread', 'Расклад на холсте')], default='tarot', max_length=20, verbose_name='Категория гадания'),
        ),
    ]
