# Generated by Django 5.2.15 on 2026-06-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0011_userreading_bot_alter_userreading_category'),
        ('tg_bot', '0038_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Например: 'DeepSeek для тестов' или 'Gemini Аккаунт 1'", max_length=100, verbose_name='Название / Описание')),
                ('api_key', models.TextField(help_text='Ключ от выбранного провайдера (AIzaSy..., sk-..., и т.д.)', verbose_name='API Ключ')),
                ('provider', models.CharField(choices=[('', 'Официальный Google AI Studio (по умолчанию)'), ('https://openrouter.ai/api/v1', 'OpenRouter'), ('https://api.deepseek.com/v1', 'DeepSeek API'), ('http://localhost:11434/v1', 'Локальный Ollama (Localhost)'), ('custom', 'Свой URL (указать в поле ниже)')], default='', max_length=100, verbose_name='Провайдер API')),
                ('custom_base_url', models.URLField(blank=True, help_text="Заполняется только если выбран вариант 'Свой URL'. Например: https://api.vllm-server.com/v1", max_length=255, null=True, verbose_name='Кастомный Базовый URL')),
                ('override_model_name', models.CharField(blank=True, help_text="Если пусто, берется дефолтная ('gemini-2.0-flash'). Для других провайдеров укажите их модель, например: 'deepseek-chat' или 'meta-llama/llama-3'", max_length=100, null=True, verbose_name='Переопределить модель')),
                ('project_identifier', models.CharField(blank=True, max_length=100, verbose_name='Идентификатор проекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_exhausted', models.BooleanField(default=False, verbose_name='Лимит исчерпан')),
                ('exhausted_until', models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tg_bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'API Ключ AI',
                'verbose_name_plural': 'API Ключи AI',
                'indexes': [models.Index(fields=['bot', 'is_active', 'is_exhausted'], name='tarot_aiapi_bot_id_91fb30_idx')],
            },
        ),
    ]
