# Generated by Django 5.2.15 on 2026-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0012_aiapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiapikey',
            name='provider',
            field=models.CharField(choices=[('https://generativelanguage.googleapis.com/v1beta', 'Официальный Google AI Studio (по умолчанию)'), ('https://openrouter.ai/api/v1', 'OpenRouter'), ('https://api.deepseek.com/v1', 'DeepSeek API'), ('http://localhost:11434/v1', 'Локальный Ollama (Localhost)'), ('custom', 'Свой URL (указать в поле ниже)')], default='https://generativelanguage.googleapis.com/v1beta', max_length=100, verbose_name='Провайдер API'),
        ),
    ]
