# Generated by Django 5.2.15 on 2026-06-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0013_alter_aiapikey_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReadingInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='Использованная модель')),
                ('status', models.CharField(choices=[('pending', 'В очереди / Обрабатывается'), ('success', 'Успешно завершено'), ('failed', 'Ошибка генерации')], default='pending', max_length=15, verbose_name='Статус запроса')),
                ('prompt_system', models.TextField(blank=True, verbose_name='Системный промпт (Инструкции)')),
                ('prompt_user', models.TextField(blank=True, help_text='Сюда входят выпавшие карты, вопрос юзера и т.д.', verbose_name='Пользовательский промпт / Контекст')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст ответа ИИ')),
                ('error_message', models.TextField(blank=True, help_text='Traceback или описание ошибки API в случае FAILED', verbose_name='Текст ошибки')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Входящие токены (Prompt)')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Исходящие токены (Completion)')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Всего токенов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан запрос')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('ai_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpretations', to='tarot.aiapikey', verbose_name='Использованный API Ключ')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretations', to='tarot.userreading', verbose_name='Расклад карт')),
            ],
            options={
                'verbose_name': 'ИИ-Интерпретация расклада',
                'verbose_name_plural': 'ИИ-Интерпретации раскладов',
                'indexes': [models.Index(fields=['reading', 'status'], name='tarot_airea_reading_f6e99c_idx'), models.Index(fields=['created_at'], name='tarot_airea_created_adfa25_idx')],
            },
        ),
    ]
