# Generated by Django 5.2.15 on 2026-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0015_aiapikey_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='original_query',
            field=models.TextField(blank=True, default='', help_text='Вопрос или тема, которую ввел пользователь перед гаданием', verbose_name='Оригинальный запрос'),
        ),
    ]
