# Generated by Django 5.2.15 on 2026-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0017_remove_aireadinginterpretation_response_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotdeck',
            name='seo_tags',
            field=models.TextField(blank=True, help_text='Мета-теги для поисковой оптимизации', null=True, verbose_name='SEO-теги'),
        ),
        migrations.AddField(
            model_name='tarotdeck',
            name='slug',
            field=models.SlugField(blank=True, help_text='Человекопонятный URL для колоды', max_length=255, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='userreading',
            name='category',
            field=models.CharField(choices=[('one', 'Одна карта'), ('tarot', 'Таро'), ('oracle', 'Оракул'), ('runes', 'Руны (Футарк)'), ('canvas_spread', 'Расклад на холсте'), ('all', 'Вся колода')], default='tarot', max_length=20, verbose_name='Категория гадания'),
        ),
    ]
