# Generated by Django 5.2.15 on 2026-06-19 17:32

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0019_update_tarot_decks_slug_seo'),
    ]

    operations = [
        TrigramExtension(),
    ]
