# Generated by Django 5.2.15 on 2026-06-19 17:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0020_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tarotdeck',
            index=django.contrib.postgres.indexes.GinIndex(fields=['seo_tags'], name='tarotdeck_seo_tags_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
