# Generated by Django 5.2.15 on 2026-06-19 17:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0021_tarotdeck_tarotdeck_seo_tags_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraculumdeck',
            name='seo_tags',
            field=models.TextField(blank=True, help_text='Мета-теги для поисковой оптимизации', null=True, verbose_name='SEO-теги'),
        ),
        migrations.AddField(
            model_name='oraculumdeck',
            name='slug',
            field=models.SlugField(blank=True, help_text='Человекопонятный URL для колоды', max_length=255, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddIndex(
            model_name='oraculumdeck',
            index=django.contrib.postgres.indexes.GinIndex(fields=['slug'], name='oraculumdeck_slug_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='oraculumdeck',
            index=django.contrib.postgres.indexes.GinIndex(fields=['seo_tags'], name='oraculumdeck_seo_tags_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
