# Generated by Django 5.2.15 on 2026-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0023_populate_oraculum_decks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_keyword', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('found_decks', models.JSONField(blank=True, null=True, verbose_name='Найденные колоды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
            ],
            options={
                'verbose_name': 'Поиск колоды',
                'verbose_name_plural': 'Поиски колод',
                'ordering': ['-created_at'],
            },
        ),
    ]
