# Generated by Django 5.2.15 on 2026-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0024_decksearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraculumdeck',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если выключено, колода не участвует в поиске и раскладах', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='tarotdeck',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если выключено, колода не участвует в поиске и раскладах', verbose_name='Активна'),
        ),
    ]
