# Generated by Django 5.2.15 on 2026-06-20 11:05

from django.db import migrations, models


def set_existing_success(apps, schema_editor):
    """Все существующие чтения помечаем как успешные."""
    UserReading = apps.get_model('tarot', 'UserReading')
    UserReading.objects.using(schema_editor.connection.alias).all().update(
        reading_status='success'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0026_alter_oraculumdeck_seo_tags_alter_tarotdeck_seo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='reading_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидание'),
                    ('initializing', 'Инициализация'),
                    ('loading', 'Загрузка карт'),
                    ('rendering', 'Создание изображения'),
                    ('uploading', 'Отправка'),
                    ('success', 'Успешно'),
                    ('error', 'Ошибка')
                ],
                default='pending',
                max_length=20,
                verbose_name='Статус выполнения'
            ),
        ),
        # Все существующие записи помечаем как успешные
        migrations.RunPython(set_existing_success, migrations.RunPython.noop),
    ]