# Generated by Django 5.2.15 on 2026-06-20 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0027_userreading_reading_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraculumdeck',
            name='seo_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список тегов для поиска (например, ['уэйт', 'waite', 'rider'])", null=True, size=None, verbose_name='SEO-теги'),
        ),
        migrations.AlterField(
            model_name='tarotdeck',
            name='seo_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список тегов для поиска (например, ['уэйт', 'waite', 'rider'])", null=True, size=None, verbose_name='SEO-теги'),
        ),
    ]
