# Generated by Django 5.2.15 on 2026-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0028_alter_oraculumdeck_seo_tags_alter_tarotdeck_seo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcarditem',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Необязательное описание карты в контексте этой колоды', null=True, verbose_name='Индивидуальное описание'),
        ),
        migrations.AddField(
            model_name='tarotcarditem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Необязательное название карты в этой колоде', max_length=255, null=True, verbose_name='Индивидуальное название'),
        ),
    ]
