# Generated by Django 5.2.15 on 2026-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0029_tarotcarditem_custom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='is_command',
            field=models.BooleanField(default=True, help_text="True — через команду (/card, /card3), False — через кнопку 'Еще карту'", verbose_name='Запущено командой'),
        ),
        migrations.AddField(
            model_name='userreading',
            name='original_message_text',
            field=models.TextField(blank=True, default='', help_text='Текст команды или сообщения, запустившего гадание', verbose_name='Текст исходного сообщения'),
        ),
    ]
