# Generated by Django 5.2.15 on 2026-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0030_userreading_is_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='initial_count',
            field=models.PositiveSmallIntegerField(default=1, help_text="Сколько карт было при создании расклада (до нажатий 'Еще карту')", verbose_name='Изначальное количество карт'),
        ),
    ]
