# Generated by Django 5.2.15 on 2026-08-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0031_userreading_initial_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCardSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.CharField(max_length=100, verbose_name='ID стикера')),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='tarot.tarotcard', verbose_name='Карта Таро')),
            ],
            options={
                'verbose_name': 'Tarot: Стикер карты Таро',
                'verbose_name_plural': 'Tarot: Стикеры карт Таро',
                'unique_together': {('tarot_card', 'sticker')},
            },
        ),
    ]
