# Generated by Django 5.2.15 on 2026-08-08 10:49
from django.db import migrations


def populate_stickers(apps, schema_editor):
    TarotCard = apps.get_model("tarot", "TarotCard")
    TarotCardSticker = apps.get_model("tarot", "TarotCardSticker")

    TAROT_STICKER_MAP = [
        {
            "card_id": "0",
            "sticker": "CAACAgIAAxUAAWp3B3TepRKhLWqpcCg-ZtNLrCgRAAKuAAPHRRUXi694Fu6gIzw9BA",
        },
        {
            "card_id": "1",
            "sticker": "CAACAgIAAxUAAWp3B3RMlYXeXm7wVOYI7rmGTKcmAAKvAAPHRRUXK1nheLLYmq09BA",
        },
        {
            "card_id": "2",
            "sticker": "CAACAgIAAxUAAWp3B3SfDbuzSHF6cjILK7DXTZlUAAKwAAPHRRUXiBhvtfZ_a3c9BA",
        },
        {
            "card_id": "3",
            "sticker": "CAACAgIAAxUAAWp3B3QI-dhWK0MNetGtJ0c1Ep6BAAKxAAPHRRUXOHH1kTK2vYE9BA",
        },
        {
            "card_id": "4",
            "sticker": "CAACAgIAAxUAAWp3B3R8ICQ_J_bacfvzlalUyyetAAKyAAPHRRUXQ18F6zWB-h09BA",
        },
        {
            "card_id": "5",
            "sticker": "CAACAgIAAxUAAWp3B3QSeTgqruwFVoXst11lj2AYAAKzAAPHRRUXK9sc28EfaEs9BA",
        },
        {
            "card_id": "6",
            "sticker": "CAACAgIAAxUAAWp3B3TBq4IYqmSbuRxrdEARckGKAAK0AAPHRRUX4EIRbb1bBEQ9BA",
        },
        {
            "card_id": "7",
            "sticker": "CAACAgIAAxUAAWp3B3QlDAZFc6S2a5YQuJt4Kv40AAK1AAPHRRUXhII_cur2Bb89BA",
        },
        {
            "card_id": "8",
            "sticker": "CAACAgIAAxUAAWp3B3R8miKUeWTtqgYnlJhhn-DnAAK5AAPHRRUXApHoPeqm-Z09BA",
        },
        {
            "card_id": "9",
            "sticker": "CAACAgIAAxUAAWp3B3SUPXdU0qlfCvv31D8QWcjQAAK3AAPHRRUXyYO02QX_-AY9BA",
        },
        {
            "card_id": "10",
            "sticker": "CAACAgIAAxUAAWp3B3RpiNJBlL_uyJzZaiCM5WmjAAK4AAPHRRUXJrOoNsFaC4E9BA",
        },
        {
            "card_id": "11",
            "sticker": "CAACAgIAAxUAAWp3B3QPc9VXJVgqhEMzjrzY5d8uAAK2AAPHRRUXks7hOM4gyFY9BA",
        },
        {
            "card_id": "12",
            "sticker": "CAACAgIAAxUAAWp3B3Q_vv0GIKPwVmn5nnWyqdm9AAK6AAPHRRUXVNpN96i2GYE9BA",
        },
        {
            "card_id": "13",
            "sticker": "CAACAgIAAxUAAWp3B3QVFZX0ryzJQq5Qr6bsgo3eAAK7AAPHRRUXQYN83xwnsSw9BA",
        },
        {
            "card_id": "14",
            "sticker": "CAACAgIAAxUAAWp3B3TfMMSTMuAk9OObgtSEjT0wAAK8AAPHRRUXlrGJ_lcbwoc9BA",
        },
        {
            "card_id": "15",
            "sticker": "CAACAgIAAxUAAWp3B3QVykhUifCGfc8b436ltr4kAAK9AAPHRRUXcnZroPxbbeI9BA",
        },
        {
            "card_id": "16",
            "sticker": "CAACAgIAAxUAAWp3B3Rxu9FZtnRqrhwtpuIznUOvAAK-AAPHRRUXFBdHISNZ9749BA",
        },
        {
            "card_id": "17",
            "sticker": "CAACAgIAAxUAAWp3B3T_n4jWCLTlCG-_QRIFPky_AAK_AAPHRRUXYdMtpuA_GXM9BA",
        },
        {
            "card_id": "18",
            "sticker": "CAACAgIAAxUAAWp3B3R9W9oROz6QAVrOuKD3QSDYAALAAAPHRRUXYe0DCpXMnAU9BA",
        },
        {
            "card_id": "19",
            "sticker": "CAACAgIAAxUAAWp3B3RP5Vkm9qGVcwy6GXDpnXVQAALBAAPHRRUXr1BqMVGAN6s9BA",
        },
        {
            "card_id": "20",
            "sticker": "CAACAgIAAxUAAWp3B3T7-PFZlOx4Z7QdATQ7EXgjAALCAAPHRRUXhBSXYjOkURY9BA",
        },
        {
            "card_id": "21",
            "sticker": "CAACAgIAAxUAAWp3B3SDQVZ6d0KyZaOY4ZRmE4tqAALDAAPHRRUX5efpBr5lFZ09BA",
        },
        {
            "card_id": "22",
            "sticker": "CAACAgIAAxUAAWp3B3S0ZgRamRFxubgITcVIgPN4AALyAAPHRRUX1E19z_KJH4E9BA",
        },
        {
            "card_id": "23",
            "sticker": "CAACAgIAAxUAAWp3B3RqKkoKd0qBSrtvUL7_0vLDAALzAAPHRRUXY6qCgpb_Ep49BA",
        },
        {
            "card_id": "24",
            "sticker": "CAACAgIAAxUAAWp3B3QnG5mb27Cyvd-CiVWu4gAB9QAC9AADx0UVFyN6DDZw0IH2PQQ",
        },
        {
            "card_id": "25",
            "sticker": "CAACAgIAAxUAAWp3B3TTJO_xxjlXjykAATK3kh5l3gAC9QADx0UVFwZF4GMHjDQTPQQ",
        },
        {
            "card_id": "26",
            "sticker": "CAACAgIAAxUAAWp3B3SEIMgftrEiH1Vm3I-6w5_SAAL2AAPHRRUXfNNs-mOgtsM9BA",
        },
        {
            "card_id": "27",
            "sticker": "CAACAgIAAxUAAWp3B3RVz2EYdIHXDbKS0wGh9EhxAAL3AAPHRRUXpwFuHKj-_TA9BA",
        },
        {
            "card_id": "28",
            "sticker": "CAACAgIAAxUAAWp3B3SfdFnxODi0de8aJZtkoMdLAAL4AAPHRRUXOK9qpqPJMsI9BA",
        },
        {
            "card_id": "29",
            "sticker": "CAACAgIAAxUAAWp3B3TzzWEsBIIGtmeYtVlLV35zAAL5AAPHRRUXuc6AyuAqhkM9BA",
        },
        {
            "card_id": "30",
            "sticker": "CAACAgIAAxUAAWp3B3S72U4-Yfjph_0ZURN6i-LfAAL6AAPHRRUXGgHIShLDt1c9BA",
        },
        {
            "card_id": "31",
            "sticker": "CAACAgIAAxUAAWp3B3QM7hmXP80GIDEUjzLs49Y5AAL7AAPHRRUXIpqkyUwOfGw9BA",
        },
        {
            "card_id": "32",
            "sticker": "CAACAgIAAxUAAWp3B3S-CWPicA1vBnDOMLwSkoQ5AALHAAPHRRUXSHRKA3YAActXPQQ",
        },
        {
            "card_id": "33",
            "sticker": "CAACAgIAAxUAAWp3B3QUOj4N1bXqFdgyTG87mkEcAALLAAPHRRUXEnf1pWDzSSg9BA",
        },
        {
            "card_id": "34",
            "sticker": "CAACAgIAAxUAAWp3B3SeOtA0bbG8r-HBemQ8Rk8mAALPAAPHRRUX06Ot3d7DxqQ9BA",
        },
        {
            "card_id": "35",
            "sticker": "CAACAgIAAxUAAWp3B3T7OydxLBUDQtt_nifXzP38AALTAAPHRRUXRPGr1r7I0lY9BA",
        },
        {
            "card_id": "36",
            "sticker": "CAACAgIAAxUAAWp3B3SMX3xaPTzLeF0UgKPeyx2FAALeAAPHRRUXvAZhxPcyjUs9BA",
        },
        {
            "card_id": "37",
            "sticker": "CAACAgIAAxUAAWp3B3TLqfFZksimR3r9xSMdl-BkAALfAAPHRRUXyTNMuDTm-lE9BA",
        },
        {
            "card_id": "38",
            "sticker": "CAACAgIAAxUAAWp3B3R4LIJXAwEp0BAjblbTlTbAAALgAAPHRRUX7ApCfHpUvoo9BA",
        },
        {
            "card_id": "39",
            "sticker": "CAACAgIAAxUAAWp3B3SX2N2jVgzRwKzbTrnCDMumAALhAAPHRRUXKjFPXk9S4kM9BA",
        },
        {
            "card_id": "40",
            "sticker": "CAACAgIAAxUAAWp3B3QoPqqyOD3ZFu3FP6c6Fjw6AALiAAPHRRUXCltL3DD1GDg9BA",
        },
        {
            "card_id": "41",
            "sticker": "CAACAgIAAxUAAWp3B3R0nu2JsGdPiLCsBOkpBDnjAALjAAPHRRUXuc9zueUvEt09BA",
        },
        {
            "card_id": "42",
            "sticker": "CAACAgIAAxUAAWp3B3Rq7ChB2lx_UGR0HpkgQa15AALkAAPHRRUX3bjb_Db0N-A9BA",
        },
        {
            "card_id": "43",
            "sticker": "CAACAgIAAxUAAWp3B3SvX_HbZJqRzWR3HFxww5FnAALlAAPHRRUXH3-DvUlK3Go9BA",
        },
        {
            "card_id": "44",
            "sticker": "CAACAgIAAxUAAWp3B3Txm9DzzPcTrGYXu4-Fz_4kAALmAAPHRRUXFQOhDemQH2o9BA",
        },
        {
            "card_id": "45",
            "sticker": "CAACAgIAAxUAAWp3B3SVqldlPeQ5INJxj1RIxM8fAALnAAPHRRUXFbEmiA_nE_k9BA",
        },
        {
            "card_id": "46",
            "sticker": "CAACAgIAAxUAAWp3B3SxIfjSGn7nzwbbq_mn1YLzAALFAAPHRRUXwyM9rcRfN_Y9BA",
        },
        {
            "card_id": "47",
            "sticker": "CAACAgIAAxUAAWp3B3SvzKXQSevDcgEUV7f1dj76AALJAAPHRRUX_ujqfJWiZS09BA",
        },
        {
            "card_id": "48",
            "sticker": "CAACAgIAAxUAAWp3B3SIo0o9KnaWvcV_by7GkmaHAALNAAPHRRUXKpFdLbJ6Thw9BA",
        },
        {
            "card_id": "49",
            "sticker": "CAACAgIAAxUAAWp3B3TsTT4QOY_X7N0qy9apu_C-AALRAAPHRRUXS3sieBZ8N5o9BA",
        },
        {
            "card_id": "50",
            "sticker": "CAACAgIAAxUAAWp3B3SqEOk-62JjdmpnGSl4OUS2AALUAAPHRRUXQRHzi1t5n1c9BA",
        },
        {
            "card_id": "51",
            "sticker": "CAACAgIAAxUAAWp3B3SwrWipXJne0BwJTdQDp5W0AALVAAPHRRUX8h2JqJOC2ic9BA",
        },
        {
            "card_id": "52",
            "sticker": "CAACAgIAAxUAAWp3B3SYT413owdZwjvI6wZAM_T5AALWAAPHRRUXP0fOCc4JrH49BA",
        },
        {
            "card_id": "53",
            "sticker": "CAACAgIAAxUAAWp3B3S8mxc0D4QZoh3l2KO9hRUgAALXAAPHRRUXnhJPrfvzfVk9BA",
        },
        {
            "card_id": "54",
            "sticker": "CAACAgIAAxUAAWp3B3QkiA87yyUHLIqfJyor_d5YAALYAAPHRRUXIiq3e7OW7AE9BA",
        },
        {
            "card_id": "55",
            "sticker": "CAACAgIAAxUAAWp3B3RXSv-Fyb4AAbxKRope9tGfYgAC2QADx0UVF-CjehnSWMPKPQQ",
        },
        {
            "card_id": "56",
            "sticker": "CAACAgIAAxUAAWp3B3RImQ0YgRQDArmMvG-FTXGrAALaAAPHRRUXRCud-5GcOSc9BA",
        },
        {
            "card_id": "57",
            "sticker": "CAACAgIAAxUAAWp3B3SE2UlZRbB3PGQEqkVVUz8kAALbAAPHRRUXa7yXG9rfOPQ9BA",
        },
        {
            "card_id": "58",
            "sticker": "CAACAgIAAxUAAWp3B3T-E6h__WXF3OUZCQMnjKddAALcAAPHRRUX7nD6kWSbKWg9BA",
        },
        {
            "card_id": "59",
            "sticker": "CAACAgIAAxUAAWp3B3StUyJyprCOibEg6YNS4N6LAALdAAPHRRUXKFylAvKfs-c9BA",
        },
        {
            "card_id": "60",
            "sticker": "CAACAgIAAxUAAWp3B3QiFRVveVbIECGwMMf7PsalAALEAAPHRRUX2eIzhu21kD49BA",
        },
        {
            "card_id": "61",
            "sticker": "CAACAgIAAxUAAWp3B3Rs2X5IwDydYv-tDlqjVg4gAALIAAPHRRUXYbQdwirEE5c9BA",
        },
        {
            "card_id": "62",
            "sticker": "CAACAgIAAxUAAWp3B3RbxmuW2XdW1fjG4URNrXvDAALMAAPHRRUXyLa2c4FT5YM9BA",
        },
        {
            "card_id": "63",
            "sticker": "CAACAgIAAxUAAWp3B3SdGY7rBQHl2LVwQLarEI70AALQAAPHRRUXdYO1UHy5xlY9BA",
        },
        {
            "card_id": "64",
            "sticker": "CAACAgIAAxUAAWp3B3SIVUfLrIRM2ZoeXB8VfsCrAALoAAPHRRUX4uuHjRG1eGI9BA",
        },
        {
            "card_id": "65",
            "sticker": "CAACAgIAAxUAAWp3B3SJxDVvs6mnc_VNHIg2XTmxAALpAAPHRRUXeY2wYyfGtz89BA",
        },
        {
            "card_id": "66",
            "sticker": "CAACAgIAAxUAAWp3B3QGcqW6QykqBGxA6y7bK90cAALqAAPHRRUXYI123yBkkug9BA",
        },
        {
            "card_id": "67",
            "sticker": "CAACAgIAAxUAAWp3B3SvhmOs_BQsWQABSmK4WT0dUwAC6wADx0UVF3f57XsRemNjPQQ",
        },
        {
            "card_id": "68",
            "sticker": "CAACAgIAAxUAAWp3B3SAMRUTyWl8EoxAxiYp9ZmYAALsAAPHRRUXy8dbQUJLnYE9BA",
        },
        {
            "card_id": "69",
            "sticker": "CAACAgIAAxUAAWp3B3Ttfws2UmAK4cRTT07DosUVAALtAAPHRRUXtLNB4VO_23o9BA",
        },
        {
            "card_id": "70",
            "sticker": "CAACAgIAAxUAAWp3B3S96fLRLKkD1Dsi7L7VOxcSAALuAAPHRRUXXDUhProke8E9BA",
        },
        {
            "card_id": "71",
            "sticker": "CAACAgIAAxUAAWp3B3Sc0xaZy6GFyGW0FPP8cB0uAALvAAPHRRUXjkrlShz0mtg9BA",
        },
        {
            "card_id": "72",
            "sticker": "CAACAgIAAxUAAWp3B3TLMd5J7eKNFamFpSI0Tj45AALwAAPHRRUXtbLiK98ZH9Q9BA",
        },
        {
            "card_id": "73",
            "sticker": "CAACAgIAAxUAAWp3B3T9U7fAYqgVgfiJVdtnoj5uAALxAAPHRRUXFOoIEYCh5fM9BA",
        },
        {
            "card_id": "74",
            "sticker": "CAACAgIAAxUAAWp3B3QQdpFWdQj1Qdo9HRHDJ6kvAALGAAPHRRUXpE92mLWTEy49BA",
        },
        {
            "card_id": "75",
            "sticker": "CAACAgIAAxUAAWp3B3TdUf9sw8h-5lq9WcLdabhrAALKAAPHRRUXQy2tK3TnExA9BA",
        },
        {
            "card_id": "76",
            "sticker": "CAACAgIAAxUAAWp3B3SkSHBH7o_wd2_1JDUEeZ7jAALOAAPHRRUXj1sSr_tzhtg9BA",
        },
        {
            "card_id": "77",
            "sticker": "CAACAgIAAxUAAWp3B3QBhjRlBYUWfyhyZ4lf_ypoAALSAAPHRRUXaMN9B3x7Uns9BA",
        },
    ]

    for item in TAROT_STICKER_MAP:
        if TarotCard.objects.filter(card_id=item["card_id"]).exists():
            card = TarotCard.objects.get(card_id=item["card_id"])
            TarotCardSticker.objects.get_or_create(
                tarot_card=card, defaults={"sticker": item["sticker"]}
            )


def reverse_populate_stickers(apps, schema_editor):
    """Удаляет все записи TarotCardSticker, созданные этой миграцией."""
    TarotCardSticker = apps.get_model("tarot", "TarotCardSticker")
    TarotCardSticker.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tarot", "0032_tarotcardsticker"),
    ]

    operations = [
        migrations.RunPython(populate_stickers, reverse_populate_stickers),
    ]
