# Generated by Django 5.2.15 on 2026-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0033_initial_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreading',
            name='category',
            field=models.CharField(choices=[('one', 'Одна карта'), ('tarot', 'Таро'), ('tarot_sticker', 'Таро Стикер'), ('oracle', 'Оракул'), ('runes', 'Руны (Футарк)'), ('canvas_spread', 'Расклад на холсте'), ('all', 'Вся колода')], default='tarot', max_length=20, verbose_name='Категория гадания'),
        ),
    ]
