# Generated by Django 5.2.15 on 2026-08-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0034_alter_userreading_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreading',
            name='has_rws_render',
            field=models.BooleanField(default=False, help_text='Был ли сгенерирован и отправлен классический вид расклада (Rider-Waite-Smith)', verbose_name='Есть RWS-рендер'),
        ),
    ]
