# Generated by Django 5.2.15 on 2026-08-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0035_userreading_has_rws_render'),
        ('tg_bot', '0038_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsfw_allowed', models.BooleanField(blank=True, default=None, help_text='None — спросить, True/False', null=True, verbose_name='18+ контент')),
                ('nsfw_spoiler', models.BooleanField(default=True, verbose_name='Спойлер 18+')),
                ('daily_enabled', models.BooleanField(default=True, verbose_name='Карта дня')),
                ('daily_spoiler', models.BooleanField(default=True, verbose_name='Спойлер daily')),
                ('daily_time', models.TimeField(blank=True, help_text='7:00 / 8:00 / 9:00 / 12:00 / 20:00', null=True, verbose_name='Время daily')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarot', to='tg_bot.tguser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Пользователь таро',
                'verbose_name_plural': 'Пользователи таро',
            },
        ),
    ]
