# Generated by Django 5.2.15 on 2026-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0036_tarotuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraculumdeck',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Колода содержит контент 18+', verbose_name='18+'),
        ),
        migrations.AddField(
            model_name='tarotdeck',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Колода содержит контент 18+', verbose_name='18+'),
        ),
    ]
