# Generated by Django 5.2.15 on 2026-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0037_oraculumdeck_is_nsfw_tarotdeck_is_nsfw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotuser',
            name='daily_spoiler',
        ),
    ]
