# Generated by Django 5.2.15 on 2026-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0038_remove_tarotuser_daily_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreading',
            name='reading_status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('initializing', 'Инициализация'), ('loading', 'Загрузка карт'), ('rendering', 'Создание изображения'), ('uploading', 'Отправка'), ('success', 'Успешно'), ('cancelled', 'Отменено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус выполнения'),
        ),
    ]
