# Generated by Django 5.2.15 on 2026-09-15 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0039_alter_userreading_reading_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotuser',
            name='admin_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='Список chat_id групп, в которых пользователь — администратор', size=None, verbose_name='Группы, где админ'),
        ),
    ]
