# Generated by Django 5.2.15 on 2026-09-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0040_tarotuser_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotuser',
            name='admin_timer',
            field=models.PositiveIntegerField(default=6, help_text='Интервал ограничения раскладов в часах для подконтрольных групп (6, 8 или 12)', verbose_name='Таймер кулдауна для админа (в часах)'),
        ),
    ]
