services:
  web:
    volumes:
      - ./app:/app           # Монтируем содержимое папки ./app в /app внутри контейнера
      - ./.env:/app/.env     # Если нужно примонтировать .env отдельно
      - static_volume:/app/static
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "${WEB_PORT:-8000}:8000"

  redis:
    ports:
      - "${OUTER_REDIS_PORT:-6379}:6379"

  db:
    ports:
      - "${OUTER_POSTGRES_PORT:-5432}:5432"

  dozzle:
    ports:
      - "${DOZZLE_PORT:-8001}:8080"