x-labels: &app_labels
  labels:
    project_name: ${PROJECT_NAME:-djangotg}

x-common-settings: &common_settings
  build:
    context: ./app
    dockerfile: Dockerfile
  volumes:
    - ./.env:/app/.env  # Примонтируем файл .env в контейнер
    - static_volume:/app/static  # Монтируем том для статики
  env_file:
    - .env
  <<: *app_labels
  depends_on:
    - db
    - redis

services:
  web:
    <<: *common_settings
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000

  bot_processor_tarot:
    <<: *common_settings
    environment:
      - INSTANCE_NAME=tarot
    command: poetry run python manage.py start_bot_processing
    restart: always

  bot_processor_cardparser:
    <<: *common_settings
    environment:
      - INSTANCE_NAME=cardparser
    command: poetry run python manage.py start_bot_processing
    restart: always

  celery:
    <<: *common_settings
    command: poetry run celery -A server worker --loglevel=info

  celery_beat:
    <<: *common_settings
    command: poetry run celery -A server beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  redis:
    image: redis:7
    <<: *app_labels
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    <<: *app_labels

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"  # Если переменная не задана, по умолчанию 80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static  # Монтируем том для статики
    depends_on:
      - web
    <<: *app_labels
    
volumes:
  postgres_data:
  static_volume:  # Общий том для статики
