# Generated by Django 5.1.5 on 2025-01-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tg_bot', '0003_tarotcard_tarotdeck_alter_parseproduct_options_and_more'), ('tg_bot', '0004_alter_tarotcarditem_unique_together_and_more')]

    dependencies = [
        ('tg_bot', '0002_parseproduct_tguser_tguserproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=10, unique=True, verbose_name='ID карты')),
                ('name', models.CharField(max_length=255, verbose_name='Название карты')),
                ('meaning', models.TextField(verbose_name='Основное значение')),
                ('meaning_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на значение')),
            ],
            options={
                'verbose_name': 'Tarot: Карта Таро',
                'verbose_name_plural': 'Tarot: Карты Таро',
            },
        ),
        migrations.CreateModel(
            name='TarotDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название колоды')),
                ('link', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на колоду')),
            ],
            options={
                'verbose_name': 'Tarot: Колода',
                'verbose_name_plural': 'Tarot: Колоды',
            },
        ),
        migrations.AlterModelOptions(
            name='parseproduct',
            options={'verbose_name': 'Card Parser: Продукт', 'verbose_name_plural': 'Card Parser: Продукты'},
        ),
        migrations.AlterModelOptions(
            name='tguserproduct',
            options={'verbose_name': 'Card Parser: Продукт пользователя', 'verbose_name_plural': 'Card Parser: Продукты пользователей'},
        ),
        migrations.CreateModel(
            name='ExtendedMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст значения')),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_meanings', to='tg_bot.tarotcard')),
            ],
            options={
                'verbose_name': 'Tarot: Расширенное толкование',
                'verbose_name_plural': 'Tarot: Расширенные толкования',
            },
        ),
        migrations.CreateModel(
            name='TarotCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=255, verbose_name='ID изображения')),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='tg_bot.tarotcard', verbose_name='Карта Таро')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tg_bot.tarotdeck', verbose_name='Колода')),
            ],
            options={
                'verbose_name': 'Tarot: Карта в колоде',
                'verbose_name_plural': 'Tarot: Карты в колодах',
                'unique_together': {('deck', 'tarot_card')},
            },
        ),
    ]
