# Generated by Django 5.1.5 on 2025-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_alter_bot_options_bot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
