# Generated by Django 5.1.5 on 2025-01-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tg_bot', '0007_category_extendedmeaning_category_new'), ('tg_bot', '0008_remove_extendedmeaning_category'), ('tg_bot', '0009_rename_category_new_extendedmeaning_category'), ('tg_bot', '0010_remove_extendedmeaning_category_and_more'), ('tg_bot', '0011_remove_extendedmeaning_category_new_and_more'), ('tg_bot', '0012_remove_extendedmeaning_category'), ('tg_bot', '0013_extendedmeaning_category'), ('tg_bot', '0014_extendedmeaning_category_base'), ('tg_bot', '0015_remove_extendedmeaning_category_base'), ('tg_bot', '0016_extendedmeaning_category_base')]

    dependencies = [
        ('tg_bot', '0006_tarotcard_is_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Tarot: Категория',
                'verbose_name_plural': 'Tarot: Категории',
            },
        ),
        migrations.RemoveField(
            model_name='extendedmeaning',
            name='category',
        ),
        migrations.AddField(
            model_name='extendedmeaning',
            name='category',
            field=models.CharField(default='1', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedmeaning',
            name='category_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='tg_bot.category'),
        ),
    ]
