# Generated by Django 5.1.5 on 2025-01-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_remove_extendedmeaning_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedmeaning',
            old_name='category_new',
            new_name='category',
        ),
    ]
