# Generated by Django 5.1.5 on 2025-01-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_remove_extendedmeaning_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedmeaning',
            name='category_new',
        ),
        migrations.AddField(
            model_name='extendedmeaning',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.category'),
        ),
    ]
