# Generated by Django 5.1.5 on 2025-01-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_remove_extendedmeaning_category_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedmeaning',
            name='category',
        ),
    ]
