# Generated by Django 5.1.5 on 2025-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_remove_extendedmeaning_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedmeaning',
            name='category',
            field=models.CharField(default='1', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
