# Generated by Django 5.1.5 on 2025-01-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0015_remove_extendedmeaning_category_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedmeaning',
            name='category_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='tg_bot.category'),
        ),
    ]
