# Generated by Django 5.1.5 on 2025-01-30 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_category_extendedmeaning_category_new_squashed_0016_extendedmeaning_category_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TarotMeaningCategory',
        ),
        migrations.CreateModel(
            name='TarotUserReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата гадания')),
                ('text', models.TextField(blank=True, verbose_name='Текст гадания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='tg_bot.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Tarot: Пользовательское гадание',
                'verbose_name_plural': 'Tarot: Пользовательские гадания',
                'indexes': [models.Index(fields=['user', 'date'], name='tg_bot_taro_user_id_50ea25_idx')],
            },
        ),
    ]
