# Generated by Django 5.1.5 on 2025-02-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0017_rename_category_tarotmeaningcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotuserreading',
            name='message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID сообщения'),
        ),
    ]
