# Generated by Django 5.1.5 on 2025-02-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0019_oraculumdeck_oraculum_squashed_0021_alter_oraculum_description_alter_oraculum_direct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oraculum',
            new_name='OraculumItem',
        ),
    ]
