# Generated by Django 5.1.5 on 2025-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0023_rename_file_id_oraculumitem_img_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип руны')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ руны')),
                ('sticker', models.CharField(max_length=100, verbose_name='ID стикера')),
                ('straight_keys', models.TextField(verbose_name='Ключи (прямое)')),
                ('straight_meaning', models.TextField(verbose_name='Значение (прямое)')),
                ('straight_pos_1', models.TextField(verbose_name='Позиция 1 (прямое)')),
                ('straight_pos_2', models.TextField(verbose_name='Позиция 2 (прямое)')),
                ('straight_pos_3', models.TextField(verbose_name='Позиция 3 (прямое)')),
                ('inverted_keys', models.TextField(verbose_name='Ключи (перевернутое)')),
                ('inverted_meaning', models.TextField(verbose_name='Значение (перевернутое)')),
                ('inverted_pos_1', models.TextField(verbose_name='Позиция 1 (перевернутое)')),
                ('inverted_pos_2', models.TextField(verbose_name='Позиция 2 (перевернутое)')),
                ('inverted_pos_3', models.TextField(verbose_name='Позиция 3 (перевернутое)')),
            ],
            options={
                'verbose_name': 'Tarot: Руна',
                'verbose_name_plural': 'Tarot: Руны',
            },
        ),
        migrations.AlterModelOptions(
            name='oraculumdeck',
            options={'verbose_name': 'Tarot: Колода оракула', 'verbose_name_plural': 'Tarot: Колоды оракула'},
        ),
        migrations.AlterModelOptions(
            name='oraculumitem',
            options={'verbose_name': 'Tarot: Карта оракула', 'verbose_name_plural': 'Tarot: Карты оракула'},
        ),
    ]
