# Generated by Django 5.1.5 on 2025-08-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0025_alter_rune_inverted_keys_alter_rune_inverted_meaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бренда')),
                ('brand_id', models.CharField(max_length=50, verbose_name='Внешний ID бренда')),
                ('product_type', models.CharField(choices=[('ozon', 'Ozon'), ('wb', 'Wildberries')], max_length=10, verbose_name='Тип площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Card Parser: Бренд',
                'verbose_name_plural': 'Card Parser: Бренды',
                'ordering': ['name'],
                'unique_together': {('brand_id', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='parseproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('subject_id', models.IntegerField(verbose_name='subjectId / category_id')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='Родительская категория')),
                ('product_type', models.CharField(choices=[('ozon', 'Ozon'), ('wb', 'Wildberries')], max_length=10, verbose_name='Тип площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Card Parser: Категория',
                'verbose_name_plural': 'Card Parser: Категории',
                'ordering': ['name'],
                'unique_together': {('subject_id', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='parseproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.category', verbose_name='Категория'),
        ),
    ]
