# Generated by Django 5.1.5 on 2025-08-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0026_brand_parseproduct_brand_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
    ]
