# Generated by Django 5.1.5 on 2025-08-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0028_remove_parseproduct_photo_id_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tguserproduct',
            unique_together=set(),
        ),
    ]
