# Generated by Django 5.1.5 on 2025-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0029_alter_tguserproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseproduct',
            name='name',
            field=models.CharField(blank=True, help_text='Официальное название товара (опционально)', max_length=255, null=True, verbose_name='Название товара'),
        ),
    ]
