# Generated by Django 5.1.5 on 2025-08-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0030_parseproduct_name'),
    ]

    operations = [
                migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ничего не делаем с БД
            state_operations=[
        migrations.RemoveField(
            model_name='parseproduct',
            name='brand',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parseproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tguserproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tguserproduct',
            name='tg_user',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ParseProduct',
        ),
        migrations.DeleteModel(
            name='TgUserProduct',
        ),
            ],
        ),
    ]