# Generated by Django 5.1.5 on 2025-08-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0031_remove_parseproduct_brand_and_more'),
    ]


    operations = [
                migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ничего не делаем с БД
            state_operations=[
        migrations.RemoveField(
            model_name='extendedmeaning',
            name='category_base',
        ),
        migrations.RemoveField(
            model_name='extendedmeaning',
            name='tarot_card',
        ),
        migrations.RemoveField(
            model_name='oraculumitem',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Rune',
        ),
        migrations.RemoveField(
            model_name='tarotcarditem',
            name='tarot_card',
        ),
        migrations.AlterUniqueTogether(
            name='tarotcarditem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tarotcarditem',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='tarotuserreading',
            name='user',
        ),
        migrations.DeleteModel(
            name='TarotMeaningCategory',
        ),
        migrations.DeleteModel(
            name='ExtendedMeaning',
        ),
        migrations.DeleteModel(
            name='OraculumDeck',
        ),
        migrations.DeleteModel(
            name='OraculumItem',
        ),
        migrations.DeleteModel(
            name='TarotCard',
        ),
        migrations.DeleteModel(
            name='TarotCardItem',
        ),
        migrations.DeleteModel(
            name='TarotDeck',
        ),
        migrations.DeleteModel(
            name='TarotUserReading',
        ),
            ],
        ),
    ]