# Generated by Django 5.1.5 on 2026-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0032_remove_extendedmeaning_category_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
    ]
