# Generated by Django 5.2.15 on 2026-06-11 05:58

import django.db.models.deletion
import tg_bot.models.file
from django.db import migrations, models

def migrate_bot_files(apps, schema_editor):
    OldBotFile = apps.get_model('tarot', 'BotFile')
    OldBotFileCache = apps.get_model('tarot', 'BotFileCache')
    NewBotFile = apps.get_model('tg_bot', 'BotFile')
    NewBotFileCache = apps.get_model('tg_bot', 'BotFileCache')

    # Перенос данных (Forward)
    for old_obj in OldBotFile.objects.all():
        new_obj = NewBotFile.objects.create(
            content_type=old_obj.content_type,
            object_id=old_obj.object_id,
            bot=old_obj.bot,
            file_id=old_obj.file_id
        )
        try:
            old_cache = OldBotFileCache.objects.get(bot_file=old_obj)
            NewBotFileCache.objects.create(
                bot_file=new_obj,
                file_path=old_cache.file_path,
                expires_at=old_cache.expires_at
            )
        except OldBotFileCache.DoesNotExist:
            continue

def reverse_migrate_bot_files(apps, schema_editor):
    # При откате мы просто очищаем новые таблицы
    # (так как старые таблицы в tarot еще не удалены, данные там целы)
    NewBotFile = apps.get_model('tg_bot', 'BotFile')
    NewBotFileCache = apps.get_model('tg_bot', 'BotFileCache')
    
    NewBotFileCache.objects.all().delete()
    NewBotFile.objects.all().delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tg_bot', '0033_bot_is_enabled'),
        ('tarot', '0003_alter_tarotcarditem_img_id_botfile'),
        ('tarot', '0005_botfilecache_delete_tarotfilecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.bot', verbose_name='Бот')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'TG file ID для ботов',
                'verbose_name_plural': 'TG file IDs для ботов',
                'unique_together': {('bot', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='BotFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='Временный file_path')),
                ('expires_at', models.DateTimeField(default=tg_bot.models.file.get_default_expires_at, verbose_name='Истекает в')),
                ('bot_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_cache', to='tg_bot.botfile', verbose_name='Bot файл')),
            ],
            options={
                'verbose_name': 'BOT FILE: Кэш путей файлов',
                'verbose_name_plural': 'BOT FILE: Кэши путей файлов',
            },
        ),
        migrations.RunPython(migrate_bot_files, reverse_code=reverse_migrate_bot_files),
    ]
