# Generated by Django 5.2.15 on 2026-06-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0034_botfile_botfilecache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botfile',
            options={'verbose_name': 'BOT FILE: Telegram File ID', 'verbose_name_plural': 'BOT FILE: Telegram File IDs'},
        ),
        migrations.AlterModelOptions(
            name='botfilecache',
            options={'verbose_name': 'BOT FILE: Кэш ссылок на файлы', 'verbose_name_plural': 'BOT FILE: Кэши ссылок на файлы'},
        ),
    ]
