# Generated by Django 5.2.15 on 2026-06-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0035_alter_botfile_options_alter_botfilecache_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='docker_instance_name',
            field=models.CharField(blank=True, help_text='Укажите имя контейнера, который должен обрабатывать этого бота', max_length=100, null=True, verbose_name='Имя докер-инстанса'),
        ),
    ]
