# Generated by Django 5.2.15 on 2026-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0036_bot_docker_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('ParserBot', 'ParserBot'), ('TarotBot', 'TarotBot'), ('GachaBot', 'GachaBot')], default='ParserBot', max_length=50, verbose_name='Тип бота'),
        ),
    ]
