# Generated by Django 5.2.15 on 2026-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(blank=True, editable=False, help_text='Telegram username бота (например: my_test_bot)', max_length=100, null=True, unique=True, verbose_name='Username бота'),
        ),
    ]
