# Generated by Django 5.2.15 on 2026-09-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0038_bot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('ParserBot', 'ParserBot'), ('TarotBot', 'TarotBot'), ('GachaBot', 'GachaBot'), ('WhirlBot', 'WhirlBot')], default='ParserBot', max_length=50, verbose_name='Тип бота'),
        ),
    ]
