# Generated by Django 5.2.15 on 2026-09-15 20:37

import django.db.models.deletion
import tg_bot.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tg_bot', '0039_alter_bot_bot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('generated_sequence', models.JSONField(help_text='Список точек генерации: [{"t": .., "amplitude": .., "pitch": ..}, ...]')),
                ('normalized_curve', models.JSONField(help_text='Точки оценки: [{"t": .., "rms": .., "pitch": ..}, ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись сирены',
                'verbose_name_plural': 'Записи сирен',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SirenRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_asset', to='whirl.sirenrecord')),
            ],
            options={
                'verbose_name': 'Картинка сирены',
                'verbose_name_plural': 'Картинки сирен',
            },
            bases=(tg_bot.models.file.BotFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SirenRecordSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound_asset', to='whirl.sirenrecord')),
            ],
            options={
                'verbose_name': 'Звук сирены',
                'verbose_name_plural': 'Звуки сирен',
            },
            bases=(tg_bot.models.file.BotFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhirlUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whirl', to='tg_bot.tguser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Пользователь Сирены',
                'verbose_name_plural': 'Пользователи Сирены',
            },
        ),
        migrations.AddField(
            model_name='sirenrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siren_records', to='whirl.whirluser'),
        ),
    ]
