# Generated by Django 5.2.15 on 2026-09-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает голосового'), ('success', 'Разобрана'), ('cancelled', 'Отменена')], default='waiting', max_length=16)),
                ('score', models.FloatField(blank=True, help_text='IoU-совпадение с эталоном, 0..100. Заполняется при переходе в SUCCESS.', null=True)),
                ('user_curve', models.JSONField(blank=True, help_text='Выровненная кривая попытки: [{"t": .., "rms": .., "pitch": ..}, ...]. Заполняется при переходе в SUCCESS.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='whirl.sirenrecord', verbose_name='Сирена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='whirl.whirluser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-created_at'],
            },
        ),
    ]
