# Generated by Django 5.2.15 on 2026-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirl', '0002_sirenattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenattempt',
            name='reply_message_id',
            field=models.BigIntegerField(blank=True, help_text="ID сообщения-приглашения ('запиши голосовое'), которое редактируется при ответе.", null=True),
        ),
    ]
