# Generated by Django 5.2.15 on 2026-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirl', '0003_sirenattempt_reply_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirenattempt',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает голосового'), ('processing', 'Обрабатывается'), ('success', 'Разобрана'), ('cancelled', 'Отменена')], default='waiting', max_length=16),
        ),
    ]
