# Generated by Django 5.1.5 on 2025-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Только одна запись в системе может быть активной.', verbose_name='Активные настройки')),
                ('picture_chat_id', models.CharField(help_text='Telegram chat ID, куда бот будет отправлять изображения для получения file_id', max_length=50, verbose_name='Chat ID для загрузки картинок')),
                ('parser_url_ozon', models.URLField(blank=True, help_text='API или веб-адрес для парсинга товаров Ozon', null=True, verbose_name='URL парсера Ozon')),
                ('parser_url_wb', models.URLField(blank=True, help_text='API или веб-адрес для парсинга товаров Wildberries', null=True, verbose_name='URL парсера Wildberries')),
                ('marketing_group_id', models.CharField(help_text='Telegram chat ID группы, куда отправляются популярные товары', max_length=50, verbose_name='Группа для вывода маркетинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Card Parser: Настройки бота',
                'verbose_name_plural': 'Card Parser: Настройки бота',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active_settings')],
            },
        ),
    ]
