# Generated by Django 5.1.5 on 2025-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0002_botsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('popular', 'Топ популярных'), ('default', 'По умолчанию')], max_length=20, verbose_name='Тип события')),
                ('caption', models.TextField(verbose_name='Текст подписи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подпись для события',
                'verbose_name_plural': 'Подписи для событий',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('event_type',), name='unique_active_event_type')],
            },
        ),
    ]
