# Generated by Django 5.1.5 on 2025-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0003_eventcaption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcaption',
            options={'verbose_name': 'Card Parser: Подпись для события', 'verbose_name_plural': 'Card Parser: Подписи для событий'},
        ),
        migrations.AddField(
            model_name='eventcaption',
            name='text',
            field=models.TextField(blank=True, help_text='Общий текст, например, перед списком или медиагруппой. Можно использовать HTML.', null=True, verbose_name='Текст выдачи'),
        ),
        migrations.AlterField(
            model_name='eventcaption',
            name='caption',
            field=models.TextField(blank=True, help_text='Текст, который будет на каждом фото (например, в медиагруппе). Можно использовать HTML.', null=True, verbose_name='Подпись к фото'),
        ),
        migrations.AlterField(
            model_name='eventcaption',
            name='event_type',
            field=models.CharField(choices=[('popular', 'Топ популярных'), ('top_brand', 'Активный бренд'), ('top_category', 'Активная категория'), ('default', 'По умолчанию')], max_length=20, verbose_name='Тип события'),
        ),
    ]
