# Generated by Django 5.1.5 on 2025-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0004_alter_eventcaption_options_eventcaption_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Уникальное имя для идентификации шаблона, например: 'Основной', 'Короткий', 'С эмодзи'", max_length=100, unique=True, verbose_name='Название шаблона')),
                ('template', models.TextField(help_text='Используйте плейсхолдеры в фигурных скобках: {brand}, {name}, {price_display}, {sizes_display}, {availability}, {link}, {sku}. Поддерживается HTML: <b>, <a href>, <s> и т.д.', verbose_name='Текст шаблона')),
                ('is_default', models.BooleanField(default=False, help_text="Будет использоваться, если в коде не указано конкретное имя шаблона. Только один шаблон может быть 'по умолчанию'.", verbose_name='Шаблон по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Card Parser: Шаблон товара',
                'verbose_name_plural': 'Card Parser: Шаблоны товаров',
                'ordering': ['name'],
            },
        ),
    ]
