# Generated by Django 5.1.5 on 2025-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0005_producttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='template',
            field=models.TextField(help_text='Используйте плейсхолдеры в фигурных скобках: {brand}, {name}, {price_display}, {sizes_display}, {availability}, {link}, {sku}. ', verbose_name='Текст шаблона'),
        ),
        migrations.AddConstraint(
            model_name='producttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_template'),
        ),
    ]
