# Generated by Django 5.1.5 on 2025-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0006_alter_producttemplate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseproduct',
            name='caption_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные для формирования подписи'),
        ),
        migrations.AlterField(
            model_name='parseproduct',
            name='caption',
            field=models.TextField(null=True, verbose_name='Подпись к фото'),
        ),
    ]
