# Generated by Django 5.1.5 on 2025-09-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardparser', '0007_parseproduct_caption_data_alter_parseproduct_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcaption',
            name='caption',
        ),
        migrations.AddField(
            model_name='eventcaption',
            name='product_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, который будет использоваться для формирования подписи под каждым фото (например, в медиагруппе).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_captions', to='cardparser.producttemplate', verbose_name='Шаблон для подписи к фото'),
        ),
    ]
