# Generated by Django 5.2.15 on 2026-06-11 18:39

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


SEED_DATA = [
    {
        "season": {
            "name": "Неделя #1: Старт",
        },
        "teams": [
            {
                "name": "Синяя команда",
                "stars": 3,
                "cards": [
                    {"name": "Циклоп", "stars": 3, "description": "Лидер Синей команды"},
                    {"name": "Джин Грей", "stars": 5, "description": "Феникс во плоти"},
                    {"name": "Шторм", "stars": 3, "description": "Повелительница погоды"},
                    {"name": "Зверь", "stars": 2, "description": "Гений и акробат"},
                    {"name": "Джубили", "stars": 1, "description": "Фейерверк мутант"},
                ],
            },
            {
                "name": "Фантастическая четвёрка",
                "stars": 3,
                "cards": [
                    {"name": "Мистер Фантастик", "stars": 3, "description": "Растягивается до невозможного"},
                    {"name": "Невидимая Леди", "stars": 3, "description": "Скрытная и смертоносная"},
                    {"name": "Человек-Факел", "stars": 2, "description": "Вспыхнет — мало не покажется"},
                    {"name": "Существо", "stars": 2, "description": "Скала с золотым сердцем"},
                    {"name": "Франклин Ричардс", "stars": 5, "description": "Сын-омега"},
                ],
            },
            {
                "name": "Громовержцы*",
                "stars": 3,
                "cards": [
                    {"name": "Баки Барнс", "stars": 4, "description": "Зимний Солдат"},
                    {"name": "Елена Белова", "stars": 3, "description": "Чёрная Вдова"},
                    {"name": "Красный Страж", "stars": 2, "description": "Советский суперсолдат"},
                    {"name": "Джон Уокер", "stars": 1, "description": "Агент США"},
                    {"name": "Таскмастер", "stars": 2, "description": "Копирует любой стиль боя"},
                ],
            },
            {
                "name": "Могучие Мстители",
                "stars": 4,
                "cards": [
                    {"name": "Капитан Америка", "stars": 4, "description": "Первый мститель"},
                    {"name": "Железный Человек", "stars": 4, "description": "Гений, миллиардер, филантроп"},
                    {"name": "Тор", "stars": 5, "description": "Бог грома"},
                    {"name": "Халк", "stars": 3, "description": "Невероятная мощь"},
                    {"name": "Чёрная Вдова", "stars": 3, "description": "Шпионка высшего класса"},
                ],
            },
        ],
    },
]


def seed_data(apps, schema_editor):
    Season = apps.get_model('roster', 'Season')
    Team = apps.get_model('roster', 'Team')
    Card = apps.get_model('roster', 'Card')

    now = timezone.now()
    week_end = now + timedelta(days=7)

    for season_data in SEED_DATA:
        season = Season.objects.create(
            name=season_data["season"]["name"],
            start_date=now,
            end_date=week_end,
            is_active=True,
        )

        for team_data in season_data["teams"]:
            team = Team.objects.create(
                season=season,
                name=team_data["name"],
                stars=team_data["stars"],
            )

            for card_data in team_data["cards"]:
                Card.objects.create(
                    team=team,
                    name=card_data["name"],
                    stars=card_data["stars"],
                    description=card_data["description"],
                )


def reverse_seed(apps, schema_editor):
    Season = apps.get_model('roster', 'Season')
    Season.objects.filter(name__startswith='Неделя #').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]