# Generated by Django 5.2.15 on 2026-06-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_seed_data'),
        ('tg_bot', '0036_bot_docker_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ролла')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='tg_bot.bot', verbose_name='Бот')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='roster.card', verbose_name='Карта')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='roster.season', verbose_name='Сезон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='tg_bot.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ролл пользователя',
                'verbose_name_plural': 'Роллы пользователей',
                'ordering': ['-rolled_at'],
                'indexes': [models.Index(fields=['user', 'season'], name='roster_user_user_id_946624_idx'), models.Index(fields=['user', 'bot', 'rolled_at'], name='roster_user_user_id_263898_idx')],
            },
        ),
    ]
