# Generated by Django 5.2.15 on 2026-06-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_userroll'),
        ('tg_bot', '0036_bot_docker_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('cooldown', 'Кулдаун (сек)'), ('daily', 'Дневной лимит'), ('bihourly', 'Двухчасовой лимит')], max_length=20, verbose_name='Тип лимита')),
                ('value', models.PositiveIntegerField(help_text='Для кулдауна — секунды, для дневного/двухчасового — кол-во попыток', verbose_name='Значение')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_limits', to='tg_bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Лимит бросков',
                'verbose_name_plural': 'Лимиты бросков',
                'unique_together': {('bot', 'limit_type')},
            },
        ),
    ]
