# Generated by Django 5.2.15 on 2026-06-11 19:00

from django.db import migrations


def seed_limits(apps, schema_editor):
    Bot = apps.get_model('tg_bot', 'Bot')
    RollLimit = apps.get_model('roster', 'RollLimit')

    bot = Bot.objects.filter(is_enabled=True).first()
    if not bot:
        return  # нет ботов — нечего настраивать

    limits = [
        ("cooldown", 60),    # 60 секунд между бросками
        ("daily", 5),        # 5 бросков в день
        ("bihourly", 10),    # 10 бросков за 2 часа
    ]

    for limit_type, value in limits:
        RollLimit.objects.get_or_create(
            bot=bot,
            limit_type=limit_type,
            defaults={"value": value},
        )


def reverse_limits(apps, schema_editor):
    RollLimit = apps.get_model('roster', 'RollLimit')
    RollLimit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_rolllimit'),
    ]

    operations = [
        migrations.RunPython(seed_limits, reverse_limits),
    ]