# Generated by Django 5.2.15 on 2026-06-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_seed_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
