# Generated by Django 5.2.15 on 2026-06-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_remove_card_image'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='tg_bot.bot', verbose_name='Бот'),
        ),
    ]
