# Generated by Django 5.2.15 on 2026-06-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_season_bot'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('roll', 'Текст броска'), ('start', 'Приветственное сообщение'), ('caption', 'Подпись к карточке')], max_length=20, verbose_name='Тип текста')),
                ('text', models.TextField(help_text='Можно использовать HTML-теги и переменные в фигурных скобках', verbose_name='Текст')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='tg_bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты ботов',
                'unique_together': {('bot', 'text_type')},
            },
        ),
    ]
