# Generated by Django 5.2.15 on 2026-06-11 21:52

from django.db import migrations


def create_default_bot_texts(apps, schema_editor):
    BotText = apps.get_model('roster', 'BotText')
    Bot = apps.get_model('tg_bot', 'Bot')

    try:
        bot = Bot.objects.get(id=1)
    except Bot.DoesNotExist:
        # Бота с ID 1 нет — пропускаем
        return

    default_texts = [
        {
            'text_type': 'start',
            'text': (
                "🦸 Привет, {first_name}!\n\n"
                "Добро пожаловать в Marvel Gacha.\n\n"
                "🎲 <b>/roll</b> — вытянуть случайную карту ({daily_limit} в день)\n"
                "📊 <b>/me</b> — посмотреть свой прогресс за неделю\n\n"
                "Собери всех героев до конца сезона!"
            ),
        },
        {
            'text_type': 'roll',
            'text': (
                "🎲 Ты вытянул карту!\n\n"
                "{stars} <b>{name}</b>\n"
                "🛡 Команда: {team}\n"
                "📝 {description}\n\n"
                "📊 Прогресс: {unique_collected}/{total_cards} уникальных карт\n\n"
                "{shop_status}" 
            ),
        },
        {
            'text_type': 'caption',
            'text': (
                "{stars} <b>{name}</b>\n"
                "{collected_status}"
            ),
        },
        {
            'text_type': 'me',
            'text': (
                "📊 <b>Твой прогресс — {season_name}</b>\n\n"
                "{teams_progress}\n"
                "🎯 <b>Итого: {collected_count}/{all_cards_count} карт</b>\n\n"
                "⚡ <b>Броски (попытки):</b>\n"
                "🟢 Доступно сегодня: {available_rolls}/{daily_limit} (кулдаун: {cooldown_sec} сек)\n"
                "{cooldown_status}"
                "💎 Премиум: {premium_status}\n\n"
                "⏳ До конца сезона: {days_text}"
            ),
        }
    ]

    for text_data in default_texts:
        BotText.objects.update_or_create(
            bot=bot,
            text_type=text_data['text_type'],
            defaults={'text': text_data['text']},
        )


def remove_default_bot_texts(apps, schema_editor):
    BotText = apps.get_model('roster', 'BotText')
    BotText.objects.filter(bot_id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_bottext'),
    ]

    operations = [
        migrations.RunPython(create_default_bot_texts, remove_default_bot_texts),
    ]