# Generated by Django 5.2.15 on 2026-06-12 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_seed_text'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolllimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolllimit',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Применить этот лимит только к премиум-пользователям', verbose_name='Премиум лимит'),
        ),
        migrations.AlterUniqueTogether(
            name='rolllimit',
            unique_together={('bot', 'limit_type', 'is_premium')},
        ),
        migrations.CreateModel(
            name='RosterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, help_text='Дает доступ к повышенным лимитам и фичам гачи', verbose_name='Премиум статус')),
                ('description', models.TextField(blank=True, help_text='Кастомное описание профиля или фандомный статус игрока', null=True, verbose_name='Описание/Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gacha_profile', to='tg_bot.tguser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
            },
        ),
    ]
