# Generated by Django 5.2.15 on 2026-06-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_alter_rolllimit_unique_together_rolllimit_is_premium_and_more'),
        ('tg_bot', '0037_alter_bot_bot_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userroll',
            name='roster_user_user_id_946624_idx',
        ),
        migrations.AddField(
            model_name='userroll',
            name='is_used_for_craft',
            field=models.BooleanField(default=False, help_text='Если True, карта была сожжена в рецепте крафта и больше не принадлежит игроку', verbose_name='Использовано для крафта'),
        ),
        migrations.AddIndex(
            model_name='userroll',
            index=models.Index(fields=['user', 'season', 'is_used_for_craft'], name='roster_user_user_id_abc61e_idx'),
        ),
    ]
