# Generated by Django 5.2.15 on 2026-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_remove_userroll_roster_user_user_id_946624_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolllimit',
            name='limit_type',
            field=models.CharField(choices=[('cooldown', 'Кулдаун (сек)'), ('daily', 'Дневной лимит'), ('bihourly', 'Двухчасовой лимит'), ('craft', 'обмен карт')], max_length=20, verbose_name='Тип лимита'),
        ),
    ]
