# Generated by Django 5.2.15 on 2026-06-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_alter_rolllimit_limit_type'),
        ('tg_bot', '0038_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RarityWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Включить/выключить данный расчет весов', verbose_name='Активно')),
                ('formula', models.TextField(default='1 / (math.factorial({star}) * ({star} + 1))', help_text='Формула расчета веса. Используйте {star} для подстановки уровня редкости (1-5). Доступны функции: math.factorial, math.pow, math.sqrt, abs, round, min, max', verbose_name='Формула веса')),
                ('coefficient', models.FloatField(default=1.0, help_text='Множитель для корректировки весов', verbose_name='Коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarity_weights', to='tg_bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Вес редкости',
                'verbose_name_plural': 'Веса редкостей',
                'indexes': [models.Index(fields=['bot', 'enabled'], name='roster_rari_bot_id_d9732e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('bot',), name='unique_enabled_per_bot')],
            },
        ),
    ]
