# Generated by Django 5.2.15 on 2026-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_rarityweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottext',
            name='text_type',
            field=models.CharField(choices=[('roll', 'Текст броска'), ('start', 'Приветственное сообщение'), ('caption', 'Подпись к карточке'), ('me', 'Данные пользователя')], max_length=20, verbose_name='Тип текста'),
        ),
    ]
