# Generated by Django 5.2.15 on 2026-08-12 12:33

from django.db import migrations, models
from django.utils.text import slugify
import re


def transliterate(text):
    """Транслитерация кириллицы в латиницу"""
    mapping = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo',
        'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
        'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
        'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'sch',
        'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya',
        'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'Yo',
        'Ж': 'Zh', 'З': 'Z', 'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M',
        'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
        'Ф': 'F', 'Х': 'H', 'Ц': 'Ts', 'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Sch',
        'Ъ': '', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya',
    }
    return ''.join(mapping.get(char, char) for char in text)


def fill_slugs(apps, schema_editor):
    Season = apps.get_model('roster', 'Season')
    for season in Season.objects.all():
        if not season.slug:
            # Транслитерируем и оставляем только первое слово
            transliterated = transliterate(season.name) if season.name else 'season'
            # Берём первое слово
            first_word = transliterated.split()[0] if transliterated.split() else 'season'
            # Применяем slugify для очистки
            base_slug = slugify(first_word)
            
            slug = base_slug
            counter = 1
            while Season.objects.filter(slug=slug).exclude(pk=season.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            season.slug = slug
            season.save(update_fields=['slug'])

def reverse_fill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_season_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slugs, reverse_fill),
    ]